/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Database.Database;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 * Clase ventana que servira para agregar a los usuarios con su contraseña y
 * los roles que este tendra en la base de datos.
 * @author Ramon Lopez
 */
public class agregarUsuarios extends javax.swing.JDialog {
    private String nombreUsuario;
    private String constrasena;
    private boolean superUser;
    private boolean createDataBases;
    private boolean createRoles;
    private boolean roles;
    private boolean backups;
    private final Database db;
    /**
     * Creates new form agregarUsuarios
     */
    public agregarUsuarios(java.awt.Frame parent, boolean modal,Database db) {
        super(parent, modal);
        initComponents();
        this.db = db;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        labelContrasena = new javax.swing.JLabel();
        checkBoxSuperUser = new javax.swing.JCheckBox();
        checkBoxCreateRoles = new javax.swing.JCheckBox();
        checkBoxCreateDataBases = new javax.swing.JCheckBox();
        checkBoxRoles = new javax.swing.JCheckBox();
        checkBoxBackups = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        botonCrearUsuario = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(601, 401));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelNombre.setText("Nombre del usuario:");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        textFieldNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(textFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 320, -1));

        labelContrasena.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        labelContrasena.setText("Contraseña:");
        jPanel1.add(labelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        checkBoxSuperUser.setText("Super usuario");
        jPanel1.add(checkBoxSuperUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        checkBoxCreateRoles.setText("Poder crear roles");
        jPanel1.add(checkBoxCreateRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        checkBoxCreateDataBases.setText("Crear base de datos");
        jPanel1.add(checkBoxCreateDataBases, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        checkBoxRoles.setText("Derecho de modificar roles");
        jPanel1.add(checkBoxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        checkBoxBackups.setText("Puede iniciar la replicación y las copias de seguridad");
        jPanel1.add(checkBoxBackups, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Selecciona roles del usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        passwordField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 320, -1));

        botonCrearUsuario.setText("Crear Usuario");
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Deseeas crear este usuario?");
        
        //confirmacion del usuario
        if (confirmacion == 0) {
            String sqlCode;
            //obtenemos los datos introducidos en la ventana
            this.nombreUsuario = textFieldNombre.getText();
            this.constrasena = passwordField.getText();
        
            //obtenemos los resultados de los checkbox
            this.backups = checkBoxBackups.isSelected();
            this.createDataBases = checkBoxCreateDataBases.isSelected();
            this.createRoles = checkBoxCreateRoles.isSelected();
            this.roles = checkBoxRoles.isSelected();
            this.superUser = checkBoxSuperUser.isSelected();
        
            //comenzamos con la creacion del codigo sql
            sqlCode = crearCodigoSql();
            //System.out.println(sqlCode);
        
            try {
                //añadimos el registro a la tabla
                db.update(sqlCode);
                JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al insertar el inversor");
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    /**
     * Crea el codigo sql que sera ejecutado para actualizar la base de datos.
     */
    private String crearCodigoSql(){
        String sql = "CREATE ROLE  \""+this.nombreUsuario+"\" WITH\n";
        
        //preguntamos por la seleccion de las check box
        //login
        sql += "\tLOGIN\n";
        
        //super usuario
        if (this.superUser == true) {
            sql += "\tSUPERUSER\n";
        }else{
            sql += "\tNOSUPERUSER\n";
        }
        
        //creador de base de datos
        if (this.createDataBases == true) {
            sql += "\tCREATEDB\n";
        }else{
            sql += "\tNOCREATEDB\n";
        }
        
        //creador de roles
        if (this.createRoles == true) {
            sql += "\tCREATEROLE\n";
        }else{
            sql += "\tNOCREATEROLE\n";
        }
        
        //INHERIT
        if (this.roles == true) {
            sql += "\tINHERIT\n";
        }else{
            sql += "\tNOINHERIT\n";
        }
        
        //replicacion
        if (this.backups == true) {
            sql += "\tREPLICATION\n";
        }else{
            sql += "\tNOREPLICATION\n";
        }
        
        //se añade limite de conecion y contraseña
        sql += "\tCONNECTION LIMIT -1";
        if (this.constrasena.equals("") == true) {
            sql += ";";
        }else{
            sql += "\n\tPASSWORD \'" + this.constrasena+"\';";
        }
        return sql;
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JCheckBox checkBoxBackups;
    private javax.swing.JCheckBox checkBoxCreateDataBases;
    private javax.swing.JCheckBox checkBoxCreateRoles;
    private javax.swing.JCheckBox checkBoxRoles;
    private javax.swing.JCheckBox checkBoxSuperUser;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
